name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python v3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: setup development environment
      run: python 1-setup-dev-conan.py
    - name: build the library
      run: |
        cd pki
        mkdir build
        cd build
        conan install ..
        cmake ..
        make --build .
    - name: run unittests of library
      run: |
        cd pki
        cd build 
        ./bin/tests
