name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup virtual environment
      run: |
        sudo apt-get install python3-venv
        python3 -m venv myvenv
        venv\Scripts\activate
    - name: setup development environment
      run: python3 1-setup-dev-conan.py
    - name: build the library
      run: |
        cd pki
        mkdir build
        cd build
        conan install ..
        cmake ..
        make --build .
    - name: run unittests of library
      run: |
        cd pki
        cd build 
        ./bin/tests
