name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup development environment
      run: python3 1-setup-dev.py
    - name: build the library
      run: cd pki && mkdir build && cd build && cmake .. && cmake --build .
    - name: run unittests of library
      run: cd pki && cd build && ./test/tests
